### ISSUE TITLE
What if finishedTimer is faster than randomTimer?

### ISSUE THREAD

**Issue by egoist** [egojump/scifi#11]
i.e. `delay < speed`, it's broken currently since we clean up everything in `finishedTimer` and also only update textContent in `randomTimer`.

I'm not sure if we should handle this case though.

**Comment by garylocke** [comment]
I was looking into merging them into one interval, possibly by setting the interval delay to the lowest of the two values, or the highest common divisor of the two, but that might create some other complications. However, I think having two intervals working together has its own complications as well.

Another option might be to require delay to be greater than or equal to speed.

**Comment by garylocke** [comment]
This should be handled by the changes in pull request #13

**Comment by garylocke** [comment]
@egoist Probably this can be closed. If you think there is still an issue, let me know and I can help address it.

**Comment by egoist** [comment]
@garylocke Thanks for your help 😄
