### ISSUE TITLE
Endless string of "undefined" prints after original content string

### ISSUE THREAD

**Issue by garylocke** [egojump/scifi#4]
In a statement on line 26 of `src/index.js`, the `finished` variable is compared against the value `content.length`. If they are equivalent, the intervals are cleared and the `scifi` function execution ends.

However, it seems that the `finished` variable can occasionally become incremented beyond the value of `content.length` before that statement is evaluated. When this happens, the content on the page is repeated appended with "undefined".
![scifi_undefined](https://user-images.githubusercontent.com/10237784/36568531-5e606a6e-17f8-11e8-9483-36a69cfcd093.png)

**Comment by garylocke** [comment]
Is the [demo site](https://scifi.egojump.com/) updated with the latest changes from pull request #6? If so, I can test for this issue on that page today.

**Comment by egoist** [comment]
@garylocke yes, it should be updated (since it's using the CDN version)

**Comment by garylocke** [comment]
Still an issue. I am noticing that I can only reproduce it by running the demo site in a background tab, which leads me to believe it may have something to do with a race condition between the two intervals, though I'm not certain of that.

Pull request #7 introduces a check on the content character before appending it to the finished string. This should eliminate the possibility of `finishedString.length` ever exceeding `content.length`, allowing the `clearInterval` statements to always execute eventually.

**Comment by garylocke** [comment]
Once the CDN version is updated, we can try again to reproduce this issue.

**Comment by egoist** [comment]
Yeah updated.

**Comment by garylocke** [comment]
Great. I'm testing this in two tabs, one of which is running in the background.

**Comment by garylocke** [comment]
Over an hour in the background without any issue. I'm comfortable calling this fixed for now if you are.

**Comment by garylocke** [comment]
I'm going to close this, since I am no longer able to reproduce the issue.
