### ISSUE TITLE
Reorder intervals to eliminate error in CircleCI build 9

### ISSUE THREAD

**Issue by garylocke** [egojump/scifi#9]
CircleCI has identified an issue where the most recent change references the `randomTimer` variable before it is defined.

**Comment by garylocke** [comment]
This has resolved the CircleCI build error.

**Comment by egoist** [comment]
Thanks, I've also updated circle settings to build pull requests. It's weird that they don't turn it on by default and I always forgot to do this..

**Comment by garylocke** [comment]
Good idea. I wondered why I wasn't seeing that output after submitting pull requests.
